# Exercise 4.4 - count
# main.tf

# Provider

provider "aws" {
  region = var.region
}

# Resources

# Three buckets with names generated by Terraform
resource "aws_s3_bucket" "bucket_count_ex_1" {
  count = 3
  region = var.region
}

# Three buckets with names generated using count.index
resource "aws_s3_bucket" "bucket_count_ex_2" {
  count = 3
  bucket = "my-test-bucket-${count.index + 1}"
  region = var.region
}

# Three buckets with names taken from the list using count.index
resource "aws_s3_bucket" "bucket_count_ex_3" {
  count = length(var.bucket_names)
  bucket = var.bucket_names[count.index]
  region = var.region
}

# List

variable bucket_names {
  description = "List with bucket names"
  type = list(string)
  default = [
    "test-bucket-1",
    "test-bucket-2",
    "test-bucket-3"
  ]
}

# Variable

variable region {
  description = "Enter region:"
  type = string
  default = "eu-west-1"
}

# Outputs

output bucket_count_ex_1 {
  value = aws_s3_bucket.bucket_count_ex_1.*.id
}

output bucket_count_ex_2 {
  value = aws_s3_bucket.bucket_count_ex_2.*.id
}

output bucket_count_ex_3 {
  value = aws_s3_bucket.bucket_count_ex_3.*.id
}
